### ISSUE TITLE
Search results change to html page

### ISSUE THREAD

**Issue by tonymcghie** [tonymcghie/CamDev#10]
The current search results are displayed as a modal.  Users need to return to search results after completing an action, however modals disappear after an actions such as a key click.

Therefore the search results need to be displayed in an html page to make it easier to return to the page.

- [x] remove ajax from main navigation
- [x] set results table to be under search
- [x] set search to be filled from get params

**Comment by mgoo** [comment]
move search parameters to get params so that the url for a search points to the search.
This will also require shifting the main navigation back to url based rather than ajax.
