### ISSUE TITLE
Sample Set -> Edit

### ISSUE THREAD

**Issue by tonymcghie** [tonymcghie/CamDev#12]
Instead of just showing the latest version, all the versions are showing in the Edit view stacked one after another.

Appears that in some instances js code previous to CAM4 is not working - is there a simply fix for this?

**Comment by tonymcghie** [comment]
Furthermore, Sample Set -> Edit is not saving to db and there appears to be a problem with version.
Suggest that the Version are displayed as bootstrap tabs, with the latest Version as the active tab.  
This maybe a problem if there are a very large number of versions, but so far Sample Sets have no more than about 5 versions.

**Comment by mgoo** [comment]
I could make the tabs scroll sideways if there are to many. Ill make a separate issue for that though as it is not important.
