### ISSUE TITLE
SampleSet View formatting

### ISSUE THREAD

**Issue by tonymcghie** [tonymcghie/CamDev#30]
Wan the View to display the SampleSet information concisely so that as much information as possible fits on the screen.
At present there is a line feed between the data label and the data.
See CAM3->SampleSet-> View to as an example.

![screenshot from 2017-12-08 22-38-42](https://user-images.githubusercontent.com/13825975/33759830-97040162-dc68-11e7-8cdb-1e31d56323bf.png)

**Comment by mgoo** [comment]
Would hiding empty fields be of value here?

**Comment by mgoo** [comment]
https://projects.invisionapp.com/freehand/document/gHghHiEUe

**Comment by mgoo** [comment]
![screenshot from 2017-12-09 13-01-55](https://user-images.githubusercontent.com/3094390/33789946-41eb9a18-dce1-11e7-8f84-9eb2c326c517.png)

**Comment by mgoo** [comment]
I have done the base of this. is on the branch CAM-4-30-details:
Things that still need to be done:
 - All the strings (Tony)
 - what columns to show and what not to show and the order (Tony)
 - make the files links and so have to get the analysis so might want to look up how to do the relationships properly betteen tables (Andrew)

The linking the models should be done in a separate issue and the analysis files can be done in a separate issue but @tonymcghie can you do the strings and order for this.

**Comment by tonymcghie** [comment]
I would prefer that all the fields are shown even if there is no data.
Then the reader knows for certain that a specific type of data is missing,
even though it has been requested for input.
